Resources:
  NasTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: systemgc-nas-registry
      AttributeDefinitions:
        - AttributeName: UUID
          AttributeType: S
      KeySchema:
        - AttributeName: UUID
          KeyType: HASH
      # Set the capacity to auto-scale
      BillingMode: PAY_PER_REQUEST