service: nas-registration-service

frameworkVersion: '>=2.0.0 <3.0.0'

provider:
  name: aws
  runtime: go1.x
  region: eu-central-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:*
        - s3:*
      Resource:
        "*"
    - Effect: Allow
      Action:
        - s3:*
      Resource: "arn:aws:s3:::rskautomation/*"
package:
 individually: true
 exclude:
   - ./**

functions:
  registry:
    handler: bin/registry
    package:
      include:
        - ./bin/registry
    events:
      - http:
          path: registry
          method: post
          cors: true
    environment:
      dynamo_table: systemgc-nas-registry
      aws_region: eu-central-1
      s3_bucket_name: rskautomation
resources:
  Resources:
    GatewayResponseDefault4XX:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: 'ApiGatewayRestApi'
    NasSub:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: systemgc-nas-registry
        AttributeDefinitions:
          - AttributeName: UUID
            AttributeType: S
        KeySchema:
          - AttributeName: UUID
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST